# Codes for running the geometric features for the cities
# 

import pandas as pd
from pathlib import Path

# merge the results into a single data panel
folder = Path("data") / "replication_geometric" / "processed"
datafiles = {
    folder / "blue_exposure_index" / "blue_exposure_index_normalized.csv": ["blue_exposure_index"],
    folder / "coastal_accessibility_index" / "coastal_proximity_normalized.csv": ["coastal_accessibility_index"],
    folder / "cropland_ratio" / "cropland_ratio_normalized.csv": ["cropland_ratio"],
    folder / "green_exposure_index" / "green_exposure_index_normalized.csv": ["green_exposure_index"],
    folder / "GDP" / "city_gdp_per_capita_normalized.xlsx": ["GDP_sum(PPP)", "GDP_per"],
    folder / "park_accessibility_index" / "park_accessibility_results_normalized.csv": ["Park Accessibility_within_300m", "Park Accessibility_within_500m"],
    folder / "patch_density_largest_patch_index_patch_dispersion_index" / "SEA_urban_park_metrics_normalized.csv": ["patch_density", "largest_patch_index", "Patch Dispersion Index"],
    folder / "per_capita_park _and_park_proportion" / "urban_park_indicators_normalized.csv": ["Park Proportion", "Per Capita Park"],
    folder / "desakota_index" / "desakota_index_crop_and_greenspace.csv": ["Desakota_Index_CropAndGreen"],
    folder / "desakota_index" / "desakota_index_crop_only.csv": ["Desakota_Index_CropOnly"]
}

mapper = {
    "coastal_accessibility_index": "Coastal Accessibility",
    "green_exposure_index": "Green Exposure Index",
    "blue_exposure_index": "Blue Exposure Index",
    "patch_density": "Patch Density",
    "largest_patch_index": "Largest Patch Index",
    "patch_dispersion_index": "Patch Dispersion Index",
    "green_space_proportion": "Green Space Proportion",
    "per_capita_green_space": "Per Capita Green Space",
    "gdp_sum(PPP)": "GDP_sum(PPP)",
    "gdp_per": "GDP_per",
    "cropland_ratio": "crop_Land",
}

# add county,lat,long to the panel
coords = pd.read_csv(Path('data') / 'GeoCoords.csv')
coords.city = coords.city.str.replace('_', ' ')
# Note: the final list of cities in the GeoIndex (153)
cities = [
    'Abra',
    'Agusan del Norte',
    'Agusan del Sur',
    'Aklan',
    'Albay',
    'Antique',
    'Aurora',
    'Bac Giang',
    'Balikpapan',
    'Banda Aceh',
    'Bandar Lampung',
    'Bandung',
    'Bangkok Metropolis',
    'Banjarnegara',
    'Basilan',
    'Bataan',
    'Batam',
    'Batangas',
    'Bekasi',
    'Benguet',
    'Biliran',
    'Binh Duong',
    'Bogor',
    'Bohol',
    'Bukidnon',
    'Bulacan',
    'Cagayan',
    'Camarines Norte',
    'Camarines Sur',
    'Camiguin',
    'Can Tho',
    'Capiz',
    'Catanduanes',
    'Cavite',
    'Cebu',
    'Chiang Mai',
    'Chonburi',
    'Cirebon',
    'Compostela Valley',
    'Cotabato (North Cotabato)',
    'Cotabato City',
    'Da Nang',
    'Dak Lak',
    'Davao Occidental',
    'Davao Oriental',
    'Davao del Norte',
    'Denpasar',
    'Depok',
    'Dong Nai',
    'Eastern Samar',
    'Guimaras',
    'HCMC',
    'Hai Duong',
    'Hai Phong',
    'Hanoi',
    'Ilocos Norte',
    'Ilocos Sur',
    'Iloilo',
    'Isabela',
    'Jakarta',
    'Johor Bahru',
    'Kalinga',
    'Kanchanaburi',
    'Kedah',
    'Kelantan',
    'Khanh Hoa',
    'Khon Kaen',
    'Kuala Lumpur',
    'La Union',
    'Laguna',
    'Lampang',
    'Lanao del Norte',
    'Lanao del Sur',
    'Leyte',
    'Maguindanao',
    'Makassar',
    'Malacca',
    'Malang',
    'Manado',
    'Marinduque',
    'Masbate',
    'Mataram',
    'Medan',
    'Metro Manila',
    'Misamis Occidental',
    'Misamis Oriental',
    'Mountain Province',
    'N Sembilan',
    'Nahon Sawan',
    'Nakhon Pathom',
    'Nakhon Ratchasrima',
    'Nakhon Si Thammarat',
    'Negros Occidental',
    'Negros Oriental',
    'Nonthaburi',
    'Northern Samar',
    'Nueva Ecija',
    'Nueva Vizcaya',
    'Occidental Mindoro',
    'Oriental Mindoro',
    'Padang',
    'Pahang',
    'Palawan',
    'Palembang',
    'Pampanga',
    'Pangasinan',
    'Pathum Thani',
    'Pekanbaru',
    'Penang',
    'Perak',
    'Perlis',
    'Phitsanulok',
    'Phuket',
    'Pontianak',
    'Putrajaya',
    'Quezon',
    'Ratchaburi',
    'Rayong',
    'Rizal',
    'Romblon',
    'Sabah',
    'Samar',
    'Samarinda',
    'Samut Prakan',
    'Samut Sakhon',
    'Saraburi',
    'Sarangani',
    'Sarawak',
    'Selangor',
    'Semarang',
    'Singapore',
    'Songkhla',
    'Sorsogon',
    'South Cotabato',
    'Southern Leyte',
    'Suigao del Norte',
    'Sultan Kudarat',
    'Sulu',
    'Surabaya',
    'Surakarta',
    'Surat Thani',
    'Surigao del Sur',
    'Tangerang',
    'Tarlac',
    'Tawi-Tawi',
    'Terengganu',
    'Ubon Ratchathani',
    'Udon Thani',
    'Yogyakarta',
    'Zambales',
    'Zamboanga Sibugay',
    'Zamboanga del Norte',
    'Zamboanga del Sur'
]
assert set(coords.city) - set(cities) == set(), "The cities in the GeoCoords.csv are not the same as the cities in the GeoIndex"

# merge the results into the coords panel
for idx, (file, columns) in enumerate(datafiles.items()):
    if file.name.endswith('.xlsx'):
        panel = pd.read_excel(file)
    else:
        panel = pd.read_csv(file)

    panel = panel[['city', *columns]]
    panel.city = panel.city.str.replace('_', ' ')
    coords = pd.merge(coords, panel, on='city', how='left')

# export the GeoIndex panel
outfile = Path('data') / "GeoIndex.xlsx"
coords.rename(columns=mapper, inplace=True)
coords.to_excel(outfile, index=False)
